spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/rmr
    username: postgres
    password: 005s005rg
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:changelog/database_changelog.yaml
default:
  page:
    number: 0
    size: 10
application:
  token:
    access:
      expires:
        time: 3600000
    refresh:
      expires:
        time: 86400000
jwt:
  secret: goshanchik
sms:
  email: ${SMS_AERO_EMAIL}
  api-key: ${SMS_AERO_API_KEY}
  sms-text: ${SMS_TEXT:Your authentication code}
  sms-sign: ${SMS_SIGN:RMR RUZAVIN}
  enabled: ${SMS_ENABLED:false}
server:
  port: 80