spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rmr
    username: postgres
    password: 005s005rg
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:changelog/database_changelog.yaml
